Table CUSTOMERS { 
CUSTOMER_ID NUMBER 
FIRST_NAME TEXT 
LAST_NAME TEXT 
FIRST_ORDER DATE 
MOST_RECENT_ORDER DATE 
NUMBER_OF_ORDERS NUMBER 
CUSTOMER_LIFETIME_VALUE NUMBER 
} 
Table ORDERS { 
ORDER_ID NUMBER 
CUSTOMER_ID NUMBER 
ORDER_DATE DATE 
STATUS TEXT 
CREDIT_CARD_AMOUNT NUMBER 
COUPON_AMOUNT NUMBER 
BANK_TRANSFER_AMOUNT NUMBER 
GIFT_CARD_AMOUNT NUMBER 
AMOUNT NUMBER 
} 
Table OLD_ORDERS { 
ORDER_ID NUMBER 
CUSTOMER_ID NUMBER 
ORDER_DATE DATE 
STATUS TEXT 
CREDIT_CARD_AMOUNT NUMBER 
COUPON_AMOUNT NUMBER 
BANK_TRANSFER_AMOUNT NUMBER 
GIFT_CARD_AMOUNT NUMBER 
AMOUNT NUMBER 
} 
Ref: CUSTOMERS.CUSTOMER_ID > ORDERS.CUSTOMER_ID 
Ref: CUSTOMERS.CUSTOMER_ID > OLD_ORDERS.CUSTOMER_ID 
